# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OpinionForTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemKeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('contributer', models.ManyToManyField(blank=True, related_name='pk_contributer', to='kaizen.Member')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_presenter', to='kaizen.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_action', models.CharField(max_length=200)),
                ('canceled_date', models.DateField(blank=True, null=True)),
                ('canceled_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('actor', models.ManyToManyField(blank=True, to='kaizen.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_idea', models.CharField(max_length=200)),
                ('target_kp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaizen.ProblemKeep')),
            ],
        ),
        migrations.AddField(
            model_name='tryaction',
            name='try_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaizen.TryParent'),
        ),
        migrations.AddField(
            model_name='review',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaizen.TryAction'),
        ),
        migrations.AddField(
            model_name='opinionfortry',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaizen.TryAction'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtg_auther', to='kaizen.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtg_presenter', to='kaizen.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtg_reporter', to='kaizen.Member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaizen.TryAction'),
        ),
    ]
